assignees = ""
authors = "Atomix Labs"
book_dir = "docs"
book_logo = ""
book_social = ""
bump_mode = "pr"
channel = "nightly"
conduct_contact = ""
crate = ""
description = "A time, counter and clock library."
kind = "lib"
license = "MIT OR Apache-2.0"
line_width = "100"
logo = ""
name = ""
repository = "atomix-labs/t2t"
runner_labels = ""
rust_version = "1.98"
