version = 2

[[profiles]]
name = "just"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "6ba63f38b4afed06274efbcfc743009c325423436c01e9b7419e6eae5d4ebfdb"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "agents"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "35bcc83714a0b3168758cf1d24f0322d58317ff2c6f13b4ef777448040d3356d"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
hook = ["default"]
readability = ["default"]
security = ["default"]

[[profiles]]
name = "cargo-workspace"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "2d4f824db2affc994c3dad1f82d7e0a08452e2aa3127a83fe7cd007e575e9769"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "mise"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "5f35eeb235a92af1d548ae0b46847ef02d0b79be82e498a6ad5ad702965c59b6"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "rust-toolchain"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "2098828db77909e211a3b1016488a529d0430df9adbdf1da34569252367412eb"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "cargo-bump"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "fe20b6a63b5f1f02c6b1266dbb8b876de4ccb2c0d1d2902f12aa949cc9184a18"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "cargo-deny"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "1320ad9b555b11a839f3102a6caf443f30d39855293254f0da53b0d4a2a6954d"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
strict = ["rust/strict"]

[[profiles]]
name = "cargo-hack"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "89b9f55f062f149f4318b00214098feb6d8c5d06ec7329ea0d5a8cc0a7461514"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "cargo-manifest"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "346ac8db84be73d1de409ceb75da49385559c104001c440bca061c9a396cbd61"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]

[[profiles]]
name = "cargo-nextest"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "e1f0ce9057a80287e9e1197dd2363d4fb4dd36ffcce6877c5df0a3845f0fbdc1"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]

[[profiles]]
name = "cargo-profiles"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "835f5a12d4dc8a22b4baaf5e30151b49881dc6daf6b248d63f332a803036e3c0"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
strict = ["rust/strict"]

[[profiles]]
name = "cargo-publish"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "781aee6a7e4c75ad4f34efedaa26a4f7d1be4abe3f13e8123cad1d9fc29391e8"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "cargo-unused"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "93112bbaf084c84be4b446bdd0e004397f4a12f4e5986a31def40654f72a4962"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
machete = ["default"]
shear = ["default"]

[[profiles]]
name = "devset"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "df355ce87f39e51efefd62f1e03bcfce88d122cae1f4992ba2b0753516378cb7"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]

[[profiles]]
name = "editorconfig"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "e1b9c57689290be868ff3a1d81e40985cbdaff418a0ac7f638d3d9b63132298a"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "git-attributes"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "1f0e46fc40b06a0acb7518bf5cbbaa084b035cf1cbc5fd969dc29897806087ab"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "git-changelog"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "20e8257770f9c9b229aec83cb429cefcde65c722833f38eb4874abe69bb902ba"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
breaking-changes = ["project/breaking-changes"]

[[profiles]]
name = "git-commits"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "75af17b14b60f0d0ba35cb0860badfea6f1d4f855cebef39d2a4d6e68a27480e"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]

[[profiles]]
name = "git-ignore"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "1fd8a8c36ef5530a189d137ec7487162280e10cc8b3aa667624a519750788425"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-automation"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "d4c7137b7067d8e479099f9e69ae5f29f3bde6b2712beee61308d2e092b01c65"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-watch"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "67ee3e4eff704a12d016dc5dc8a33b97cc5602bc9ecc6195803c6fbb7e407d3e"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-bump"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "55b30dd357613cb91c404112d694f49ead49b3c1e4ae7a4710c91d1885283617"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-ci"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "512f1bb5ceec9d9c79dcb9ecc8d1df6d1d9cab27a2d14b8adf054c5baa47b4d3"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
pages = ["mdbook/pages"]

[[profiles]]
name = "github-dependabot"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "0d391809a41f9ba8259d4f442be6cd02f0d5f7f66f7e0e6ab51315b84b6d5fcf"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-labels"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "5cdaf8b8099ae95dd53b343f5b1e2b466d09f3549c8efccf2c2528b6bc848800"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-nightly"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "e8e3696326126d5cc05832597deae130648325d5096facdbfc4bf923fea7db99"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "github-release"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "67e4308e71230374a5b2d62c18b456a7c91e80014b44511a557278d9505b3654"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]

[[profiles]]
name = "github-templates"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "3efad25496ef2c40602486477f54fccf6d4688eeb5bce3b31ddcada16863e5cb"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
discussions = ["target"]

[[profiles]]
name = "github-workflow-lint"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "87401a21b27ccd7a988d0dccdc2c18e8947161b89104fb6ec32b869d36bf7466"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
actionlint = ["default"]
policies = ["default"]
zizmor = ["default"]

[[profiles]]
name = "dprint"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "cc751577affd1ff40fa8689d13eefb6247c8fe20c069b386575ae0131fb82ee5"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "markdown"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "75442bf10ec9c3f3dcd3e9e15d427f2fc9fecfc42375fc08ce3346969b617b6e"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "lychee"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "1d2c03ac88735d7cce4a53416f3871c1ddaacd887a6c6c85614cfc6fcf1c7c1c"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "mdbook-tool"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "cb1f9e1264ba2549d29990d93cab21c61c0bfe371ceb3b963a0416760ecbdc62"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "mdbook"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "4d6a246859f376391414017706f83f7174cbd7b48c858ed3ee842ec3e0d1ed9b"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
api = ["default"]
katex = ["default"]
links = ["default"]
pages = ["default"]

[[profiles]]
name = "project"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "ac564877c23d815d346f30e782f3307654ed391e0e25e7e7afbade3d5e9a107d"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
breaking-changes = ["default"]
conduct = ["rust/oss"]
contributing = ["default"]
devset-badge = ["target"]
license = ["default"]
readme = ["default"]
security = ["default"]
support = ["rust/oss"]

[[profiles]]
name = "rust-clippy"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "e0fd7ce1d0d694f30545e2dc69203ff879a1538e6f12c2dcaba9233adb61cc9c"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "rust-doc"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "ed68122ab075e8df101a325a898c2a4f7bc11985244a26980a37fdc14d23e7c9"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
strict = ["rust/strict"]

[[profiles]]
name = "rust-fmt"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "95cc546d1d0b3910bfc6b87db3effeba8cdcb5e7fb436601d248c868f5708b07"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "rust-lints"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "03e74c852566c8c5f17eaf5478ee4966626f1f27256960b5dea96fe960d99ee1"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["rust/agents"]
nightly = ["rust/nightly"]
strict = ["rust/strict"]

[[profiles]]
name = "setup"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "1bd7b53df0941ae15675911224793c59cac3f2a9dbb8ff32d5bd0b380a9a44de"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "shell"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "1c5096572121f2c6f701d2447286eed65623592fd977d8670b4f7e684e72c72c"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
lint = ["default"]

[[profiles]]
name = "spelling"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "172e999cb3e525669e536963dde38ed2632c29e3b4813d064967595f0e670e22"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "toml"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "e0932ead42c8f206dbe4e3b14d9cb88ce0630787f9ecc7379ddc68ab4e5e114d"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "yaml"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "00f89f851f790fbb9ed82d614f4a02a629a3c2a01dc9941676e3454b51091353"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "rust"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "e5193968ff930229ca287a3ee492fc021964321597aa13a2295006a7382b21d7"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[profiles.features]
agents = ["target"]
docs = ["target"]
nightly = ["target"]
oss = ["target"]
publish = ["target"]
strict = ["target"]

[[profiles]]
name = "vscode"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "c741706d51d6a5ee5b63225a8b154478e59a62bc15620be9dadd4864eb110627"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"

[[profiles]]
name = "rust-msrv"
rev = "ed08936b8dfd96e1f490603cc7ba129ba287b20d"
digest = "44e5631c6d7f05f1e43c7ecd9d2508d2ac27c6edaab73718192d67f3fb2c7b0b"

[profiles.source]
git = "https://github.com/atomix-labs/atxp"
tag = "v0.19.1"
